# Generated by Django 6.0.2 on 2026-04-13 00:49

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FleetUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Ambulância Alfa-01', max_length=100)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponível'), ('BUSY', 'Em Atendimento'), ('MAINTENANCE', 'Em Manutenção')], default='AVAILABLE', max_length=20)),
                ('capabilities', models.JSONField(default=dict, help_text="Ex: {'uti': true, 'oxygen': true, 'capacity': 2}")),
            ],
            options={
                'db_table': 'fleet_units',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['capabilities'], name='capabilities_idx', opclasses=['jsonb_path_ops'])],
            },
        ),
    ]
