# Generated by Django 6.0.2 on 2026-04-26 21:09

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fleetunit',
            options={'ordering': ['unit_type', 'name'], 'verbose_name': 'Unidade de Frota', 'verbose_name_plural': 'Unidades de Frota'},
        ),
        migrations.RenameIndex(
            model_name='fleetunit',
            new_name='capabilities_gin_idx',
            old_name='capabilities_idx',
        ),
        migrations.AddField(
            model_name='fleetunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fleetunit',
            name='unit_type',
            field=models.CharField(choices=[('USB', 'Unidade de Suporte Básico'), ('USA', 'Unidade de Suporte Avançado'), ('UR', 'Unidade de Resgate')], db_index=True, default='USB', help_text='Classificação operacional da viatura (USB / USA / UR). Primeiro critério de triagem no despacho.', max_length=3, verbose_name='tipo de unidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fleetunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='fleetunit',
            name='capabilities',
            field=models.JSONField(default=dict, help_text='Capacidades específicas da unidade. Exemplo: {"uti": true, "oxygen": true, "cardiac_monitor": true, "capacity": 2}', verbose_name='capacidades'),
        ),
        migrations.AlterField(
            model_name='fleetunit',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='localização atual'),
        ),
        migrations.AlterField(
            model_name='fleetunit',
            name='license_plate',
            field=models.CharField(max_length=20, unique=True, verbose_name='placa'),
        ),
        migrations.AlterField(
            model_name='fleetunit',
            name='name',
            field=models.CharField(help_text='Ex: Ambulância Alfa-01', max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='fleetunit',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponível'), ('BUSY', 'Em Atendimento'), ('MAINTENANCE', 'Em Manutenção')], db_index=True, default='AVAILABLE', max_length=20, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='fleetunit',
            index=models.Index(fields=['unit_type', 'status'], name='fleet_type_status_idx'),
        ),
    ]
